#YAML
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webthing-go
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: webthing-go
    spec:
      containers:
      - image: rzrfreefr/webthing-go:latest
        name: webthing-go
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: webthing-go
spec:
  ports:
  - nodePort: 30080
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: webthing-go
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
